-- Table: h_user_roles
CREATE TABLE h_user_roles
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id             NUMBER,
    h_oper         VARCHAR2(1),
    name           VARCHAR2(30) NOT NULL,
    description    VARCHAR2(250),
    create_user_id NUMBER       NOT NULL,
    create_date    TIMESTAMP    NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP
);

-- Table: h_user_status (renamed from h_status)
CREATE TABLE h_user_status
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h_oper         VARCHAR2(1),
    id             NUMBER,
    name           VARCHAR2(50) NOT NULL,
    description    VARCHAR2(250),
    create_user_id NUMBER       NOT NULL,
    create_date    TIMESTAMP    NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP
);

-- Table: h_images
CREATE TABLE h_images
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h_oper         VARCHAR2(1),
    id             NUMBER,
    image          BLOB      NOT NULL,
    create_user_id NUMBER    NOT NULL,
    create_date    TIMESTAMP NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP
);

-- Table: h_groups
CREATE TABLE h_groups
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h_oper         VARCHAR2(1),
    id             NUMBER,
    name           VARCHAR2(25) NOT NULL,
    description    VARCHAR2(250),
    images_id      NUMBER,
    create_user_id NUMBER       NOT NULL,
    create_date    TIMESTAMP    NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP
);

-- Table: h_tags
CREATE TABLE h_tags
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h_oper         VARCHAR2(1),
    id             NUMBER,
    name           VARCHAR2(50) NOT NULL,
    description    VARCHAR2(250),
    create_user_id NUMBER       NOT NULL,
    create_date    TIMESTAMP    NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP
);

-- Table: h_users
CREATE TABLE h_users
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h_oper         VARCHAR2(1),
    id             NUMBER,
    login          VARCHAR2(10) NOT NULL,
    name           VARCHAR2(20) NOT NULL,
    second_name    VARCHAR2(20),
    lastname       VARCHAR2(20) NOT NULL,
    password       VARCHAR2(40) NOT NULL,
    salt           VARCHAR2(40) NOT NULL,
    refresh_token  NUMBER,
    role           NUMBER       NOT NULL,
    birthdate      DATE         NOT NULL,
    email          VARCHAR2(40) NOT NULL,
    status         NUMBER       NOT NULL,
    create_user_id NUMBER       NOT NULL,
    create_date    TIMESTAMP    NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP
);

-- Table: h_users_sessions
CREATE TABLE h_users_sessions
(
    user_id NUMBER PRIMARY KEY,
    token          NUMBER,
    refresh_token  NUMBER,
    CONSTRAINT fk_h_users FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Table: h_posts
CREATE TABLE h_posts
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h_oper         VARCHAR2(1),
    id             NUMBER,
    content        VARCHAR2(4000) NOT NULL,
    post_date      NUMBER         NOT NULL,
    user_id        NUMBER         NOT NULL,
    create_user_id NUMBER         NOT NULL,
    create_date    TIMESTAMP      NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP,
    CONSTRAINT fk_h_users_id FOREIGN KEY (user_id) REFERENCES h_users (h_id)
);

-- Table: h_comments
CREATE TABLE h_comments
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h_oper         VARCHAR2(1),
    id             NUMBER,
    comment_value  VARCHAR2(2000) NOT NULL,
    users_id       NUMBER         NOT NULL,
    posts_id       NUMBER         NOT NULL,
    create_user_id NUMBER         NOT NULL,
    create_date    TIMESTAMP      NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP
);

-- Table: h_group_users
CREATE TABLE h_group_users
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h_oper         VARCHAR2(1),
    groups_id      NUMBER    NOT NULL,
    users_id       NUMBER    NOT NULL,
    create_user_id NUMBER    NOT NULL,
    create_date    TIMESTAMP NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP
);

-- Table: h_posts_images
CREATE TABLE h_posts_images
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h_oper         VARCHAR2(1),
    posts_id       NUMBER    NOT NULL,
    images_id      NUMBER    NOT NULL,
    create_user_id NUMBER    NOT NULL,
    create_date    TIMESTAMP NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP
);

-- Table: h_posts_tags
CREATE TABLE h_posts_tags
(
    h_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    h_oper         VARCHAR2(1),
    posts_id       NUMBER    NOT NULL,
    tags_id        NUMBER    NOT NULL,
    create_user_id NUMBER    NOT NULL,
    create_date    TIMESTAMP NOT NULL,
    mod_user_id    NUMBER,
    mod_date       TIMESTAMP
);

COMMIT;
