CREATE USER mh_meowhub IDENTIFIED BY "Mwhb2024!" PROFILE mh_profile;
GRANT CONNECT, RESOURCE TO mh_meowhub;

CREATE USER mh_chats IDENTIFIED BY "Mwhb2024!mwhb" ACCOUNT LOCK;
ALTER USER mh_chats QUOTA 200M ON DATA;

CREATE USER mh_users IDENTIFIED BY "Mwhb2024!mwhb" ACCOUNT LOCK;
ALTER USER mh_users QUOTA 100M ON DATA;

CREATE USER mh_matching IDENTIFIED BY "Mwhb2024!mwhb" ACCOUNT LOCK;
ALTER USER mh_matching QUOTA 100M ON DATA;

CREATE USER mh_posts IDENTIFIED BY "Mwhb2024!mwhb" ACCOUNT LOCK;
ALTER USER mh_posts QUOTA 200M ON DATA;

CREATE USER mh_profiles IDENTIFIED BY "Mwhb2024!mwhb" ACCOUNT LOCK;
ALTER USER mh_profiles QUOTA 200M ON DATA;

CREATE USER mh_user_relations IDENTIFIED BY "Mwhb2024!mwhb" ACCOUNT LOCK;
ALTER USER mh_user_relations QUOTA 50M ON DATA;