name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pobranie kodu źródłowego
      - name: Checkout code
        uses: actions/checkout@v4

      # Instalacja Node.js i zależności
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      # Budowanie aplikacji Vite
      - name: Build project
        working-directory: ./frontend
        run: npm run build

      # Przesyłanie artefaktów (pliki zbudowane w folderze "dist")
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Wdrożenie na GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
